- CODE_OF_CONDUCT.md
- Sources/Afluent/Extensions/RecursiveLockExtensions.swift
- Sources/Afluent/Protocols/AsynchronousUnitOfWork.swift
- Sources/Afluent/Workers/SingleValueSubject.swift
- Tests/AfluentTests/WorkerTests/SingleValueSubjectTests.swift
Added a single value subject. This is roughly equivalent to the following combine chain:
let subject = PassthroughSubject<MyType, Error>().first().share()
In other words, it will emit a single value eventually, and won't ever send more, but subscriptions after it has emitted a value will just get that value (or error). 
This can be really helpful when bridging to synchronous APIs. The whole thing is thread-safe, so there's no need to synchronize calls to `send`
> Single value subject

- Sources/Afluent/DeferredTask.swift
- Sources/Afluent/Protocols/AsynchronousUnitOfWork.swift
- Sources/Afluent/Workers/AssertNoFailure.swift
- Sources/Afluent/Workers/Catch.swift
- Sources/Afluent/Workers/Decode.swift
- Sources/Afluent/Workers/Delay.swift
- Sources/Afluent/Workers/Encode.swift
- Sources/Afluent/Workers/EraseToAnyAsynchronousUnitOfWork.swift
- Sources/Afluent/Workers/FlatMap.swift
- Sources/Afluent/Workers/HandleEvents.swift
- Sources/Afluent/Workers/Map.swift
- Sources/Afluent/Workers/MapError.swift
- Sources/Afluent/Workers/Materialize.swift
- Sources/Afluent/Workers/ReplaceError.swift
- Sources/Afluent/Workers/ReplaceNil.swift
- Sources/Afluent/Workers/Retain.swift
- Sources/Afluent/Workers/Retry.swift
- Sources/Afluent/Workers/RetryAfterFlatMapping.swift
- Sources/Afluent/Workers/Share.swift
- Sources/Afluent/Workers/SingleValueChannel.swift
- Sources/Afluent/Workers/SingleValueSubject.swift
- Sources/Afluent/Workers/Timeout.swift
- Sources/Afluent/Workers/Zip.swift
- Tests/AfluentTests/WorkerTests/SingleValueChannelTests.swift
This shares a lot of similarities with SingleValueSubject. The key difference is that the `send` methods are `async`. This provides similar ergonomics to the channels in swift-async-algorithms. In general, because this is able to use swift concurrency under the hood, it should be preferred. 
This remains valuable for single-value notifications...but becomes less convenient for bridging to synchronous APIs than `SingleValueSubject` does.
> [single-value-channel] - Single Value Channel added - TT

- Sources/Afluent/Workers/WithUnretained.swift
- Tests/AfluentTests/WorkerTests/WithUnretainedTests.swift
Extension of AsynchronousUnitOfWork with a new Operator `WithUnretained`
Provides an unretained, safe to use (i.e. not implicitly unwrapped), reference to an object along with the events emitted by the operator. In the case the provided object cannot be retained successfully, the sequence will throw.
Heavily based on the RxSwift operator - `withUnretained` - https://github.com/ReactiveX/RxSwift/blob/main/RxSwift/Observables/WithUnretained.swift - The difference is that here it will throw if didn't manage to unwrap. As we don't care for the stream
> Extension of AsynchronousUnitOfWork - WithUnretained.

- Sources/Afluent/Extensions/AsyncSequenceExtensions.swift
- Sources/Afluent/SequenceOperators/DematerializeSequence.swift
- Sources/Afluent/SequenceOperators/MaterializeSequence.swift
- Tests/AfluentTests/SequenceTests/AnyAsyncSequenceTests.swift
- Tests/AfluentTests/SequenceTests/CatchSequenceTests.swift
- Tests/AfluentTests/SequenceTests/HandleEventsSequenceTests.swift
- Tests/AfluentTests/SequenceTests/MaterializeSequenceTests.swift
- Tests/AfluentTests/SequenceTests/RetryAfterFlatMappingSequenceTests.swift
- Tests/AfluentTests/SequenceTests/RetryOnAfterFlatMappingSequenceTests.swift
- Tests/AfluentTests/SequenceTests/RetryOnSequenceTests.swift
- Tests/AfluentTests/SequenceTests/RetrySequenceTests.swift
Added a materialize operator. This emits all events the `AsyncSequence` receives into an `Event` which lets you build custom transforms and manage side-effects.
> Materialize sequence

- Sources/Afluent/SequenceOperators/HandleEventsSequence.swift
- Tests/AfluentTests/SequenceTests/HandleEventsSequenceTests.swift
HandleEventsSequence had a bug where receiveComplete was never called, that has been fixed
> Fix handleEventsSequence bug

- Sources/Afluent/SequenceOperators/MapErrorSequence.swift
- Tests/AfluentTests/SequenceTests/MapErrorSequenceTests.swift
Added a `MapError` sequence, similar to Combine's `mapError` operator.
> [maperror-sequence] - Added a mapError operator to AsyncSequence - TT

- Sources/Afluent/Workers/SingleValueSubject.swift
- Tests/AfluentTests/WorkerTests/SingleValueSubjectTests.swift
On main, `SingleValueSubject` has a bug when `send` and `execute` are run concurrently:
1. `execute` begins, sees no value or error sent so creates a `withUnsafeThrowingContinuation` closure
2. `send` begins and sets the value or error
3. `execute` overrides the value set by `send` with a continuation, thus never sending
The behavior seems to contradict the documentation for `withUnsafeThrowingContinuation`:
> The body of the closure executes synchronously on the calling task
Nonetheless, this bug is easily reproducible by running either of the new tests repeatedly with the existing `SingleValueSubject` behavior.
> Fix concurrency bug in SingleValueSubject

- Sources/Afluent/SequenceOperators/BreakpointSequence.swift
- Sources/Afluent/SequenceOperators/HandleEventsSequence.swift
- Sources/Afluent/SequenceOperators/PrintSequence.swift
- Sources/Afluent/Workers/Assign.swift
- Sources/Afluent/Workers/Breakpoint.swift
- Sources/Afluent/Workers/HandleEvents.swift
- Sources/Afluent/Workers/Print.swift
- Tests/AfluentTests/SequenceTests/HandleEventsSequenceTests.swift
- Tests/AfluentTests/WorkerTests/HandleEventsTests.swift
Adds the following to `HandleEventsSequence`:
* `receiveMakeIterator`: called when `makeAsyncIterator` is called
* `receiveNext`: called when `next` is called
Adds the following to `HandleEvents`:
* `receiveExecute`: called immediately prior to the upstream `operation` execution
The availability of these operators would be especially useful for testing when using Afluent.
Open to feedback / suggestions.
> HandleEventsSequence + HandleEvents Additions

- Sources/Afluent/Subscription/AnyCancellable.swift
- Tests/AfluentTests/SubscriptionTests.swift
Adds a `subscribe` operator to `AsyncSequence` that returns an `AnyCancellable`. I've tried to make the function as similar to Combine's `Publisher.sink(receiveCompletion:receiveValue:)` as possible.
I've nested the `Completion` type in `AsyncSequences` to mirror how `Subscribers.Completion` is nested.
Please nitpick the signatures / types!
Bonus: if / when this operator is merged, an `AsyncSequence` can be created and subscribed to in a synchronous context!
> Add subscribe to AsyncSequence

- .github/workflows/trunk.yml
- Sources/Afluent/SequenceOperators/CollectSequence.swift
- Tests/AfluentTests/SequenceTests/CollectSequenceTests.swift
- Tests/AfluentTests/SequenceTests/HandleEventsSequenceTests.swift
Added a `collect` operator that works like Combine's. It's worth noting that some folks seem to expect `collect` to gather all elements and return, but that's not generally how operator style APIs function. Instead, just like Combine, this collects all elements into an array and then emits that array as a sequence of 1. 
This means that if you want to use `collect` like some other async libraries have it, you'd call `collect().first()` or `collect().sink()`.
> [collect-sequence] - Added Collect operator - TT

- README.md
- Sources/Afluent/SequenceOperators/CollectSequence.swift
- Sources/Afluent/SequenceOperators/Deferred.swift
- Sources/Afluent/SequenceOperators/JustSequence.swift
- Tests/AfluentTests/SequenceTests/DeferredSequenceTests.swift
- Tests/AfluentTests/SequenceTests/JustSequenceTests.swift
- Tests/AfluentTests/SubscriptionTests.swift
Created a `Just` sequence to match Combine's and updated documentation to reflect that Afluent supports the vast majority of combine operators for sequences now.
> Added Just, updated docs - TT

- Sources/Afluent/SequenceOperators/DecodeSequence.swift
- Sources/Afluent/SequenceOperators/DematerializeSequence.swift
- Sources/Afluent/SequenceOperators/EncodeSequence.swift
- Sources/Afluent/SequenceOperators/HandleEventsSequence.swift
- Sources/Afluent/SequenceOperators/MaterializeSequence.swift
- Sources/Afluent/Workers/SingleValueChannel.swift
Actor reentrancy is hard to reason about. As a consequence there's a bug I still don't 100% understand with SingleValueChannel that running repeated tests caught where it'd deadlock. That has now been fixed! 
I also made some minor refactors on creating upstream iterators a little earlier in the lifecycle.
> Fixed a deadlock bug with SingleValueChannel

- Sources/Afluent/SequenceOperators/FlatMapSequence.swift
- Tests/AfluentTests/SequenceTests/FlatMapSequenceTests.swift
The `flatMap` operator that comes with the standard library has the unfortunate side-effect of only creating one subscription to the upstream at a time. This is is opposite of the Combine behavior and reared its ugly head when testing the GroupBy operator. This PR adds a FlatMap implementation with no such limitations.
> FlatMap max subscriptions

- Sources/Afluent/SequenceOperators/CollectSequence.swift
- Tests/AfluentTests/SequenceTests/CollectSequenceTests.swift
Previously the `collect` sequence operator had a nasty habit of just always returning the collected array instead of emitting it once then finishing its own sequence.
> [collect-sequence-finish-fix] - Collect actually finishes! - TT

- Sources/Afluent/Protocols/AsynchronousUnitOfWork.swift
- Tests/AfluentTests/DeferredTaskTests.swift
- Tests/AfluentTests/SequenceTests/ThrottleSequenceTests.swift
There was an issue in `DeferredTask`s not being cancelled properly when called with `execute()` or `result`. This fixes that by using `withTaskCancellationHandler` to cancel the inner task if the given task context is cancelled.
Added tests fail w/o the fix and reliably succeed w/ the fix.
> allow for DeferredTask to be cancelled with execute and result

- Package.swift
- Package@swift-5.10.swift
- Package@swift-5.8.swift
- Package@swift-5.9.swift
- Sources/Afluent/Rethrow.swift
- Sources/Afluent/SequenceOperators/PlatformLock.swift
- Sources/Afluent/SequenceOperators/ShareSequence.swift
- Tests/AfluentTests/SequenceTests/ShareSequenceTests.swift
I must admit to some frustration, the swift-async-algorithms team has had a PR with 2 reasonable "Broadcast" algorithms for more than a year and a half without merging. There's some other really good PRs open as well. 
Given that Afluent is trying to occupy this strange space between the standard library and swift-async-algorithms this puts me in an awkward position. To get out of it I've decided to introduce an "Experimental" API. This is basically where I pull in the work that swift-async-algorithms hasn't. Expect API surfaces here to deprecate and eventually become obsoleted if and when Apple finally introduces them into the swift-async-algorithms project. 
Until then, pulling in Broadcast unlocks a host of new possibilities, such as subjects. To utilize this, simply: …
> Added in experimental SPI and pulled in Broadcast Algorithm

- Package.swift
Update to use the non-deprecated Package API for Swift 6.
Was previously using: https://developer.apple.com/documentation/packagedescription/package/init(name:defaultlocalization:platforms:pkgconfig:providers:products:dependencies:targets:swiftlanguageversions:clanguagestandard:cxxlanguagestandard:)
Now using: https://developer.apple.com/documentation/packagedescription/package/init(name:defaultlocalization:platforms:pkgconfig:providers:products:dependencies:targets:swiftlanguagemodes:clanguagestandard:cxxlanguagestandard:)
> Fix Package API used for Swift 6

- Sources/Afluent/Additions/QueueExecutor.swift
- Sources/Afluent/Protocols/AsynchronousUnitOfWork.swift
- Sources/Afluent/Subscription/AnyCancellable.swift
- Tests/AfluentTests/QueueExecutorTests.swift
- Tests/AfluentTests/WorkerTests/ExecuteOnTaskExecutorTests.swift
- Tests/AfluentTests/WorkerTests/ExecutePriorityTests.swift
This PR adds the ability to specify a [task executor preference](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0417-task-executor-preference.md) and task priority. Note that the former is only available with Swift 6.
Additionally, a `QueueExecutor` implementation of `TaskExecutor` has been added that allows for Tasks to be executed with GCD while still retaining the benefits of using Swift concurrency (e.g. `TaskLocal` values).
The `run` and `execute` APIs on `AsynchronousUnitOfWork` have additional parameters added to forward a `taskExecutor` and `priority`. Calling without any arguments is still supported. By providing these parameters, the work is executed with the specified parameters.
The addition of a `QueueExecutor` additionally allows for consumers to schedule …
> Add task executor and priority features

- .github/workflows/CI.yml
- .github/workflows/PR_CI.yml
- .github/workflows/trunk.yml
- Package.swift
- Sources/Afluent/PassthroughSubject.swift
- Tests/AfluentTests/PassthroughSubjectTests.swift
This PR adds a much needed PassthroughSubject to Afluent! This mimics the behavior of Combine's PassthroughSubject and supports multiple consumers.
> Added PassthroughSubject

- Tests/AfluentTests/WorkerTests/ExecutePriorityTests.swift
We encountered some flakes in the `ExecutePriorityTest.executesWithExpectedPriority` test case when the expected `currentPriority` was incorrect.
I _believe_ this has to do with the `currentPriority` changing while a Task is executing.
It appears that [Swift's own tests around priority escalation](https://github.com/swiftlang/swift/blob/f6a0f5527db09da6b50c3ea4040207bf9244ba65/test/Concurrency/async_task_priority.swift#L107) need to wait for priority to be escalated while the Task is executing.
I did try out a fix that waited for the Task's priority to match what we expected, but even with a 100 millisecond timeout, this sometimes was not enough time.
Since this test is really about testing the priority we asked for, not necessarily the one we get, I decided to ignore what Swift sets the …
> Fix ExecutePriorityTests

- Sources/Afluent/Errors/TimeoutError.swift
- Sources/Afluent/Workers/Timeout.swift
- Tests/AfluentTests/WorkerTests/TimeoutTests.swift
The use of `CancellationError` by the `Timeout` type makes it difficult to discern when a timeout has occurred v.s. when some work has been cancelled via other methods.
This MR proposes that we change the error thrown to a specific `Error` type that makes it clear that failure occurred due to timeout.
When thrown, the localized description takes the form: `Timed out after waiting 0.01 seconds` (example)
> Adds Timeout error type

- Sources/Afluent/SequenceOperators/TimerSequence.swift
- Tests/AfluentTests/SequenceTests/TimerSequenceTests.swift
- Tests/AfluentTests/WaitUntilCondition.swift
- Tests/AfluentTests/WaitUntilScheduled.swift
Adds a `TimerSequence` type that emulates the behavior of [Timer.TimerPublisher](https://developer.apple.com/documentation/foundation/timer/timerpublisher).
Example usage:
```swift
Task {
for try await instant in TimerSequence.publish(every: .seconds(1)) {
print(instant)
}
}
// prints:
// Instant(offset: 1 second)
// Instant(offset: 2 seconds)
// Instant(offset: 3 seconds)
// ...
```
[Since the usage of Timer doesn't seem to be advocated for in Swift concurrency](https://forums.swift.org/t/structured-concurrency-with-timers/47980), I chose to not define this type on `Timer`, but rather have it as part of the global namespace.
Additionally, as part of the effort to transition from things like `TimeInterval` and `Date`, I've chosen to have this sequence emit `clock.now`, which is of type …
> Add TimerSequence type

- .github/workflows/docc-release.yml
- .github/workflows/release.yml
- Package.swift
- Package@swift-5.10.swift
- Package@swift-5.8.swift
- Package@swift-5.9.swift
- README.md
- Sources/AfluentTesting/WaitUntilCondition.swift
- Sources/AfluentTesting/WaitUntilScheduled.swift
- Tests/AfluentTests/SequenceTests/TimerSequenceTests.swift
Adds an AfluentTesting target that contains some of the test functions that we'd like to make available publicly.
Adds the `wait(until:timeout)` and `Task.waitUntilScheduled` test utilities to a new AfluentTesting target.
For `waitUntilScheduled`, I changed `sending @isolated(any)` to `@Sendable`, which is supported by Swift < 6 and Swift 6 compilers. @Tyler-Keith-Thompson if there's a particular reason why you used the former, let me know, because we'd need to use a conditional compiler directive to support Swift < 6.
Adds DocC publishing for the AfluentTesting target, in addition to the Afluent target.
I did this by using a [reusable workflow](https://docs.github.com/en/actions/sharing-automations/reusing-workflows). Open to suggestions on if there's a more preferred way to achieve the …
> AfluentTesting target

- Sources/AfluentTesting/WaitUntilCondition.swift
Missing some availability annotations that prevented building for non-macOS platforms.
The only way we can enable automated testing for this is to use a macOS runner or figure out some way to setup a simulator on linux.
> Fix building for non-macOS platforms

- Sources/Afluent/Workers/Share.swift
- Tests/AfluentTests/WorkerTests/ShareTests.swift
The `Share` worker was not properly cancelling upstream work when it itself was cancelled.
The reason for this is that the `Share` worker creates its own `Task` that it manages. That means that in addition to cancelling the `TaskState` (which is the storage that controls the executing work from the consumer's perspective), we also need to cancel that internally stored `Task`.
A test has been added to prove that the upstream is properly cancelled (this test does not pass with the previous implementation). I've verified the test succeeds on repeated runs.
I've also made 1 change to another `ShareTests` test that did not seem to be robust in its validation.
> Fix Share worker cancellation of Upstream worker

- Sources/Afluent/Workers/ShareFromCache.swift
- Tests/AfluentTests/WorkerTests/ShareFromCacheTests.swift
This reverts commit 268acffc5a5979d461a75674943e7dc44aed6500.
Unfortunately variadic generics was causing compiler build issues when using Swift 5.10 (via Xcode 15.4).
> Revert "Refactor ShareFromCache to use variadic generics (#162)"

- Sources/Afluent/AUOWCacheStrategies/AUOWCache+CacheUntilCompletionOrCancellation.swift
- Sources/Afluent/AUOWCacheStrategies/AUOWCache+CancelAndRetry.swift
- Sources/Afluent/AUOWCacheStrategies/AUOWCacheStrategy.swift
- Sources/Afluent/AsynchronousUnitOfWorkCache.swift
- Sources/Afluent/Workers/ShareFromCache.swift
As suggested in #164, this PR refactors `AUOWCache.Strategy` to be a protocol that may be implemented by consumers. The refactor attempts to minimize the possibility of consumer breakage.
> Refactor AUOWCache.Strategy to be a protocol

- Sources/Afluent/SequenceOperators/ThrottleSequence.swift
- Sources/Afluent/Workers/SingleValueSubject.swift
In consumer usage of the throttle operator, we observed hangs in UI tests that only occurred when the `throttle` operator was used.
This seems to be related to the `while` loop that was used to await next elements. If the upstream was not emitting more elements, it seems the `while` loop caused issues with app execution.
To Do:
> Refactor Throttle operator to avoid while loops

- Sources/Afluent/Workers/EraseToAnyAsynchronousUnitOfWork.swift
- Tests/AfluentTests/WorkerTests/EraseToAnyAsynchronousUnitOfWorkTests.swift
- Tests/AfluentTests/WorkerTests/ShareTests.swift
The `AsynchrononsUnitOfWork` protocol has several functions that have default implementations that _can_ be implemented explicitly by workers (e.g. `cancel()`). However, the `AnyAsynchronousUnitOfWork` worker does not properly propagate these calls to the upstream, instead relying upon the default implementations, which results in these explicit implementations not being called.
One concrete example of this is the `Share` worker, which implements its own `cancel()` function. This is not properly being called when this worker is erased as an `AnyAsynchronousUnitOfWork` (see added test, which fails on the current production implementation).
In this PR, I've added all `AsynchronousUnitOfWork` protocol properties and functions explicitly to the `AnyAsynchronousUnitOfWork` type to utilize the …
> Add fix for AnyAsynchrononsUnitOfWork upstream not being called for some protocol function calls

- Sources/Afluent/Additions/URLSessionAdditions.swift
With [this PR](https://github.com/swiftlang/swift-corelibs-foundation/pull/4970), the async/await URLSession functions are now available on other OS's, but only in swift 6.
Updates `URLSessionAdditions.swift` to also check for swift 6, and enable these urlsession -> afluent bridge functions when possible.
> Enable URLSession additions on other OS's in swift 6

- Sources/Afluent/SequenceOperators/OutputSequence.swift
- Tests/AfluentTests/SequenceTests/OutputSequenceTests.swift
Implement `output(in:)` similar to Combine - https://developer.apple.com/documentation/combine/publisher/output(in:)
Incoming ranges are reduced to `Range<Int>` same way as Apple does it in Combine.
> Implement output in

- README.md
- Sources/Afluent/AsyncSequenceCache.swift
- Sources/Afluent/CurrentValueSubject.swift
- Sources/Afluent/PassthroughSubject.swift
- Sources/Afluent/SequenceOperators/ShareFromCacheSequence.swift
- Sources/Afluent/SequenceOperators/ShareSequence.swift
- Tests/AfluentTests/CurrentValueSubjectTests.swift
- Tests/AfluentTests/PassthroughSubjectTests.swift
- Tests/AfluentTests/SequenceTests/ShareFromCacheSequenceTests.swift
- Tests/AfluentTests/SequenceTests/ShareSequenceTests.swift
- Tests/AfluentTests/SequenceTests/TimerSequenceTests.swift
Previously the `share` operator on `AsyncSequence` was behind `@_spi(Experimental)` because it'd been taken from swift-async-algorithms. This also prevented `shareFromCache`, `CurrentValueSubject`, and `PassthroughSubject` from being exposed without the SPI. Now that we've had some users in production with it I think it's about time to get rid of the SPI protections. They've honestly been more irritating than helpful.
> [publicize-share] - Remove all SPI protections - TT

- .github/workflows/MERGE_QUEUE.yml
- .trunk/trunk.yaml
- Sources/Afluent/SequenceOperators/ScanSequence.swift
- Tests/AfluentTests/SequenceTests/ScanSequenceTests.swift
[Scan](https://developer.apple.com/documentation/combine/publisher/scan(_:_:)) is an operator provided by Combine that's handy for creating streams that know how to operate over previous values. For example, you can use a trick like this to look at the previous and current value in a sequence:
```swift
scan(Optional<(Output?, Output)>.none) { ($0?.1, $1) }
.compactMap { $0 }
```
This would allow you to build up sequences that only emit when the upstream changes its value. 
The addition to Afluent furthers the parity between Afluent and Combine.
> [scan-operator] - Added a scan operator - TT
